apiVersion: batch/v1
kind: Job
metadata:
  name: baseloadandrollout-elasticity
  namespace: loadtester
  labels:
    app: baseloadandrollout-elasticity
spec:
  template:
    spec:
      nodeName: k8s-cluster3-7
      containers:
      - name: baseloadandrollout-elasticity
        image: pingpong3107/gatling-loadtests
        command: ["./gradlew",  "gatlingRun-elasticity.SimBaseLoadThenRollout"]
        env:
          - name: pollingIntervalsHost
            value: "ota-tester-pi-service.ota-tester.svc.cluster.local:8080/"
       #   - name: imageId1
      #      value: "8mb.bin"
          - name: basePollLoad
            value: "20"
          - name: heavyLoad
            value: "10"
        volumeMounts:
        - mountPath: /usr/gatling/build/reports/
          name: "gatlingvol"
      restartPolicy: Never
      volumes:
      - name: gatlingvol
        persistentVolumeClaim:
          claimName: gatling-results-claim-new
