apiVersion: batch/v1
kind: Job
metadata:
  name: getnewimage-elasticity
  namespace: loadtester
  labels:
    app: getnewimage-elasticity
spec:
  template:
    spec:
      containers:
      - name: getnewimage-elasticity
        image: pingpong3107/gatling-loadtests
        command: ["./gradlew",  "gatlingRun-elasticity.SimGetNewImageElasticity"]
        env:
          - name: pollingIntervalsHost
            value: "ota-tester-pi-service.ota-tester.svc.cluster.local:8080/"
        volumeMounts:
        - mountPath: /usr/gatling/build/reports/
          name: "gatlingvol"
      restartPolicy: Never
      volumes:
      - name: gatlingvol
        persistentVolumeClaim:
          claimName: gatling-results-claim-new