apiVersion: batch/v1
kind: Job
metadata:
  name: pollingintervalsnondelta
  namespace: loadtester
  labels:
    app: pollingintervalsnondelta
spec:
  template:
    spec:
      nodeName: k8s-cluster3-7
      containers:
      - name: pollingintervalsnondelta
        image: pingpong3107/gatling-loadtests
        command: ["./gradlew",  "gatlingRun-pollingIntervals.SimPollingIntervalsDefaultTestDelta"]
        env:
          - name: numberOfCars
            value: "200"
          - name: pollingIntervalsHost
            value: "ota-tester-pi-service.ota-tester.svc.cluster.local:8080/"
          - name: imageId1
            value: "mediumImage.bin"
          - name: imageId2
            value: "mediumImage2.bin"
          - name: waitTimeForScndRollout
            value: "90"
        volumeMounts:
        - mountPath: /usr/gatling/build/reports/
          name: "gatlingvol"
      restartPolicy: Never
      volumes:
      - name: gatlingvol
        persistentVolumeClaim:
          claimName: gatling-results-claim-new