apiVersion: batch/v1
kind: Job
metadata:
  name: pushnondelta
  namespace: loadtester
  labels:
    app: pushnondelta
spec:
  template:
    spec:
      nodeName: k8s-cluster3-7
      containers:
      - name: pushnondelta
        image: pingpong3107/gatling-loadtests
        command: ["./gradlew","gatlingRun-withBroker.SimPushDefaultNonDelta"]
        env:
          - name: numberOfCars
            value: "1000"
          - name: wBHost
            value: "ota-tester-service.ota-tester.svc.cluster.local:8080/"
          - name: brokerHost
            value: "rabbit-service.broker-rabbit.svc.cluster.local"
          # - name: imageId1
          #   value: "mediumImage.bin"
        volumeMounts:
        - mountPath: /usr/gatling/build/reports/
          name: "gatlingvol"
      restartPolicy: Never
      volumes:
      - name: gatlingvol
        persistentVolumeClaim:
          claimName: gatling-results-claim-new


  
  
    
  
  

