apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatling-results-claim
  namespace: loadtester
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: default