apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: database-mongo
spec:
  accessModes:
    - ReadWriteMany
  #volumeName: pv-mongo
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-cephfs