apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
  namespace: database-mongo
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-cephfs
  hostPath:
    path: /data/mongo
